---

variables:
  CR_PROVIDER: "gitlab"
  CR_MODEL: 
    value: "gpt-3.5-turbo-0613"
    description: "The model to use"
  CR_TEMPERATURE: 
    value: "0.0"
    description: "The temperature"
  CR_MAX_SUPPORTED_TOKENS: 
    value: "4096"
    description: 'The maximum supported tokens'
  CR_MAX_COMPLETION_TOKENS: 
    value: "2048"
    description: 'The maximum supported completion tokens'
  CR_TARGET_BRANCH:
    value: "new-branch"
    description: "The branch where any changes will be committed"
  CR_TYPE: 
    value: "review"
    description: "The type of action to perform"    
  CR_TARGET_FILES: 
    value: ""
    description: "Optional: List of comma separated values containing target files.  If empty, the entire repo will be used."


workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "push"
      when: never
    - when: always

# Uncomment to run
stages:
  - run_docker

run_docker:
  stage: run_docker
  image: 
    name: case.artifacts.medtronic.com/ventilation-docker-dev-local/prototypes/code-reviewer:latest 
    entrypoint: [""]
  script:
    - python3 -u /src/app.py
  tags:
    - weilea2-laptop
